server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always

spring:
    application:
        name: sectors-api
    main:
        allow-bean-definition-overriding: true
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: true
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: false
                format_sql: false
                enable_lazy_load_no_trans: true

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/master.yml

springdoc:
    swagger-ui:
        url: /docs/openapi.yml
        path: /swagger-ui.html
        enabled: true
    api-docs:
        resolve-schema-properties: true
        enabled: true
    paths-to-match: /**

logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

jwt:
    secret-key: ${JWT_SECRET}
    expiration-ms: 3600000
