openapi: 3.1.1
info:
    title: Helmes Sectors API
    version: 1.0.0

paths:
    /api/v1/users/{userId}/applications:
        post:
            summary: Create application for user
            description: Creates a new application for the specified user
            operationId: createApplication
            tags:
                - Applications
            parameters:
                -   name: userId
                    in: path
                    required: true
                    description: User identifier
                    schema:
                        type: integer
                        format: int64
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ApplicationDTO'
            responses:
                '201':
                    description: Application successfully created
                '400':
                    description: Invalid request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
                '404':
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
                '500':
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'

    /api/v1/sectors/tree:
        get:
            summary: Returns sectors as tree
            operationId: getSectorTree
            tags:
                - Sectors
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/SectorDTO'
                '400':
                    description: Invalid request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
                '500':
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
components:
    schemas:
        SectorDTO:
            type: object
            description: Sector tree node
            properties:
                id:
                    type: integer
                    format: int32
                    example: 6
                name:
                    type: string
                    example: Food and Beverage
                parentId:
                    type: integer
                    format: int32
                    nullable: true
                    example: 1
                sectorLevel:
                    type: integer
                    format: int32
                    example: 2
                children:
                    type: array
                    items:
                        $ref: '#/components/schemas/SectorDTO'
        ApplicationDTO:
            type: object
            required:
                - applicantName
                - sectorIds
                - agreedToTerms
            properties:
                applicantName:
                    type: string
                    minLength: 2
                    maxLength: 240
                    example: John Doe
                sectorIds:
                    type: array
                    minItems: 1
                    items:
                        type: integer
                        format: int64
                    example: [ 1, 5, 12 ]
                agreedToTerms:
                    type: boolean
                    example: true
        ErrorDTO:
            type: object
            properties:
                code:
                    type: string
                    description: Server error code
                description:
                    type: string
                    description: Detailed description of the error
