openapi: 3.1.1
info:
    title: Helmes Sectors API
    version: 1.0.0

servers:
    -   url: http://localhost:8080

paths:
    /api/v1/users/register:
        post:
            summary: Register new user
            operationId: registerUser
            tags:
                - Users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserRegisterDTO'
            responses:
                '201':
                    description: User successfully registered
                    content:
                        application/json:
                            schema:
                                type: integer
                                format: int64
                                description: Created user ID
                '400':
                    description: Validation error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
    /api/v1/users/login:
        post:
            summary: Authenticate user
            operationId: loginUser
            tags:
                - Users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserAuthDTO'
            responses:
                '200':
                    description: Authentication successful
                    content:
                        application/json:
                            schema:
                                type: string
                                description: JWT access token
                '401':
                    description: Invalid credentials
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'

    /api/v1/users/applications:
        post:
            summary: Create application for authenticated user
            operationId: createApplication
            tags:
                - Applications
            security:
                -   bearerAuth: [ ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ApplicationDTO'
            responses:
                '201':
                    description: Application successfully created
                '400':
                    description: Validation error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
                '403':
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
                '404':
                    description: Related entity not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'

    /api/v1/sectors/tree:
        get:
            summary: Returns sectors as tree
            operationId: getSectorTree
            tags:
                - Sectors
            security:
                -   bearerAuth: [ ]
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/SectorDTO'
                '500':
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDTO'
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        UserAuthDTO:
            type: object
            required:
                - username
                - password
            properties:
                username:
                    type: string
                    minLength: 5
                    maxLength: 20
                    example: edgar123
                password:
                    type: string
                    format: password
                    minLength: 8
                    example: strongPassword123
        UserRegisterDTO:
            allOf:
                -   $ref: '#/components/schemas/UserAuthDTO'
        ApplicationDTO:
            type: object
            required:
                - applicantName
                - sectorIds
                - agreedToTerms
            properties:
                applicantName:
                    type: string
                    minLength: 2
                    maxLength: 240
                    example: John Doe
                sectorIds:
                    type: array
                    minItems: 1
                    items:
                        type: integer
                        format: int64
                    example: [ 1, 5, 12 ]
                agreedToTerms:
                    type: boolean
                    example: true
        SectorDTO:
            type: object
            description: Sector tree node
            properties:
                id:
                    type: integer
                    format: int32
                    example: 6
                name:
                    type: string
                    example: Food and Beverage
                parentId:
                    type: integer
                    format: int32
                    nullable: true
                    example: 1
                sectorLevel:
                    type: integer
                    format: int32
                    example: 2
                children:
                    type: array
                    items:
                        $ref: '#/components/schemas/SectorDTO'
        ErrorDTO:
            type: object
            properties:
                code:
                    type: string
                    example: INVALID_CREDENTIALS
                description:
                    type: string
                    example: Invalid username or password
